In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sqlalchemy import create_engine

In [2]:
DB_USER = "postgres"
DB_PASSWORD = "1234"
DB_HOST = "localhost"
DB_PORT = "5432"
DB_NAME = "onee_predictive_maintenance"

engine = create_engine(
    f"postgresql+psycopg2://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
)

print("Connexion à PostgreSQL réussie !")

Connexion à PostgreSQL réussie !

In [3]:
query = "SELECT COUNT(*) AS total FROM iot_measurements;"

pd.read_sql(query, engine)

    total
0  201000

In [4]:
df = pd.read_sql("SELECT * FROM iot_measurements;", engine)

print(df.shape)

(201000, 34)

In [5]:
df.head()

,measurement_id,timestamp,city,district,sensor_id,network_type,equipment_type,temperature_c,humidity_percent,pressure_bar,...,ambient_temperature,peak_hour,weekend,holiday,season,failure_history_last_30_days,failure_history_last_year,anomaly_score,failure_probability,target_failure
0,1,2022-11-05 19:20:00,Casablanca,District_5,SNR-00386,Water,pumping_station,20.4,77.8,5.25,...,16.9,1,1,0,Autumn,0,2,0.4659,0.2924,0
1,2,2022-03-18 07:40:00,Marrakech,District_2,SNR-00038,Water,pumping_station,20.6,38.1,5.45,...,19.7,1,0,0,Spring,0,1,0.3489,0.0454,0
2,3,2024-06-18 12:50:00,Laayoune,District_3,SNR-01023,Water,pumping_station,37.2,42.9,4.07,...,30.7,0,0,0,Summer,0,3,0.6294,0.4939,1
3,4,2022-03-19 09:40:00,Tangier,District_1,SNR-00204,Water,water_tank,24.7,77.1,3.37,...,16.0,1,1,0,Spring,2,1,0.3702,0.4404,1
4,5,2021-05-14 09:20:00,Dakhla,District_2,SNR-00585,Electricity,substation,41.9,47.2,NaN,...,19.9,1,0,0,Spring,1,2,0.5890,0.1825,0

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 201000 entries, 0 to 200999
Data columns (total 34 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   measurement_id                201000 non-null  int64
 1   timestamp                     201000 non-null  datetime64[us]
 2   city                          201000 non-null  str
 3   district                      201000 non-null  str
 4   sensor_id                     201000 non-null  str
 5   network_type                  201000 non-null  str
 6   equipment_type                201000 non-null  str
 7   temperature_c                 198884 non-null  float64
 8   humidity_percent              198985 non-null  float64
 9   pressure_bar                  100056 non-null  float64
 10  water_flow_l_min              100027 non-null  float64
 11  voltage_v                     98962 non-null   float64
 12  current_a                     98973 non-null   float64
 13  power_factor                  98997 non-null   float64
 14  frequency_hz                  98964 non-null   float64
 15  energy_consumption_kwh        98940 non-null   float64
 16  vibration_mm_s                199035 non-null  float64
 17  noise_db                      198999 non-null  float64
 18  equipment_age_years           201000 non-null  float64
 19  maintenance_delay_days        198995 non-null  float64
 20  operating_hours               198983 non-null  float64
 21  rainfall_mm                   199035 non-null  float64
 22  wind_speed                    198940 non-null  float64
 23  dust_level                    199025 non-null  float64
 24  ambient_temperature           199036 non-null  float64
 25  peak_hour                     201000 non-null  int64
 26  weekend                       201000 non-null  int64
 27  holiday                       201000 non-null  int64
 28  season                        201000 non-null  str
 29  failure_history_last_30_days  201000 non-null  int64
 30  failure_history_last_year     201000 non-null  int64
 31  anomaly_score                 198991 non-null  float64
 32  failure_probability           201000 non-null  float64
 33  target_failure                201000 non-null  int64
dtypes: datetime64[us](1), float64(20), int64(7), str(6)
memory usage: 52.1 MB